### ISSUE TITLE
more time fields on creating an election

### ISSUE THREAD

**Issue by gnokii** [fedora-infra/nuancier#103]
as we created nuancier, we wanted to make it simple and left out some time fields and opened the elections automatically. Times changed, it becomes harder for me to moderate all until election opens and with the publishing in the Fedora Magazine its also hard to write it fast enough. So we need 2 more times

*submission end
*publishing date

**Comment by pypingou** [comment]
The submission end date has been added in https://github.com/fedora-infra/nuancier/pull/116

For the publishing date, I am less convinced. What is the harm to have the results publicly available there before publishing them on Fedora Magazine?

@jflory7 any thoughts on this?

**Comment by pypingou** [comment]
@mairin do you also have thoughts on this?

**Comment by jflory7** [comment]
@pypingou Hey, sorry, I just found this buried in a lot of other emails.

I don't see the harm in having the information shown publicly on Nuancier once the election ends, unless there's any kind of manual moderation that needs to happen from when the elections close to when the results are officially announced. As far as I know, there isn't, but I'm not sure.

**Comment by pypingou** [comment]
So the change for adding submission end date has been done in https://github.com/fedora-infra/nuancier/pull/116

If we're fine with having the results published on nuancier before they are published on fedora magazine, then I think we can close this ticket.
I will proceed and do so, feel free to re-open if you disagree.

Thanks! :)
