### ISSUE TITLE
Vagrant devel setup fails during ansible playbook phase

### ISSUE THREAD

**Issue by 00willo** [fedora-infra/nuancier#117]
Currently, by following the instructions to setup the dev environment in the README fails when performing from a freshly cloned git repo.  It fails with a ansible playbook error as files/alembic.ini is not present in the git repo.  

Looking at the commits, I can see that:
02Dec13 - .gitignore had alembic.ini added (969c2208aee08bb5c18ea333182df6636f757c2a)
13Dec13 - Vagrant files adding that would have included alembic.ini (e8ba9d5fe0a9f620e3383573ca19a49ba3e5fb3a)

Consequently, alembic.ini from the ansible role wasn't committed.

Working on a quick PR to resolve.

**Comment by pypingou** [comment]
Fixed in #118
