### ISSUE TITLE
Update doc

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/nuancier#58]
I was pointed out that the doc isn't up to date, they do not work if you follow them verbatim, we should improve on this :)
https://github.com/fedora-infra/nuancier/pull/57

Ralph fixed one thing on #59 (see below) but there might be more, we should go through and fix them.

**Comment by ralphbean** [comment]
Part of this is taken care of by #59.

**Comment by zeus9** [comment]
I would like to contribute

**Comment by vatsala** [comment]
PR https://github.com/fedora-infra/nuancier/pull/65

**Comment by pypingou** [comment]
The goal of this ticket was not to change the doc but to adjust it to see what is missing and what needs adjustments.
Thank you for your work on improving the current wording, there were apparently a number of mistakes, but PR#65 does not solve this ticket :)

**Comment by vatsala** [comment]
@pypingou Ok, I will run throught the doc again and add whatever is missing and whatever needs adjustments.

Also replying to your various code review comments on the PR
