### ISSUE TITLE
No module named flask.ext.fas_openid

### ISSUE THREAD

**Issue by ishankhare07** [fedora-infra/nuancier#61]
on doing 
```shell
python createdb.py
```
i get the above error, while i have installed python-fedora, flask, SQLAlchemy and all other dependencies

**Comment by pypingou** [comment]
using pip the file is in ``python-fedora``, but if you install it via rpm, then you need ``python-fedora-flask``

**Comment by ishankhare07** [comment]
thanks, ```python-fedora-flask``` worked!
