### ISSUE TITLE
Make results and stats links a littler easier to distinguish

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/nuancier#62]
There are two links on each line of https://apps.fedoraproject.org/nuancier/results/ but this is clearly not easy to figure out.

We should fix this :)

**Comment by ShaguftaMethwani** [comment]
https://github.com/fedora-infra/nuancier/pull/63

**Comment by pypingou** [comment]
Fixed in https://github.com/fedora-infra/nuancier/pull/67
