### ISSUE TITLE
Place a button to the deadlines in the instructions page

### ISSUE THREAD

**Issue by robyduck** [fedora-infra/nuancier#75]
I think it would be a good idea to add to the contributing instructions also a button to the "elections" schedule. Actually people get a lot of informations on how a wallpaper should look like, but they don't get informations about submission deadlines, voting periods, etc. unless they click on the elections tab in the top navigation bar.
On the bottom of the contributing instructions there is a "Contribute" button for the actual submission process. Maybe beside that button (or below, but near to it) we could add a link to the schedule, just to inform all people about the submissions schedule.

Yes, I know we have them in the wiki and on fedoramagazine.org (thx gnokii), but an additional link in the page people are looking at when starting to submit their wallpaper image, wouldn't hurt IMO.
Thanks.

**Comment by pypingou** [comment]
Rather than a link I am pondering between:

- just display the table for the elections open
- just provide the end date for contributing next to the button

Thoughts?

**Comment by robyduck** [comment]
I'm fine with a small table, even better because it states the actual deadlines, not the previous ones we have in the elections tab.

**Comment by pypingou** [comment]
> not the previous ones we have in the elections tab.

I'm not sure to understand what you mean here :)

**Comment by robyduck** [comment]
Oh yeah, sorry. I meant we should display just the actual submission schedule, which is why I say your proposal is better than just a link to the election page.
In the election page we have also other (already closed) submissions for older Fedora release versions.

**Comment by farhaanbukhsh** [comment]
Hey @pypingou  , I am new to contributing to fedora can you guide me to fix this issue?

**Comment by pypingou** [comment]
Hey @farhaanbukhsh cool! Welcome :)

The first step would be for you to get a local instance of nuancier running. The steps should be mentioned in the documentation but feel free to ping here on in #fedora-apps on freenode (IRC) if you run into any trouble.

**Comment by pypingou** [comment]
Fixed by https://github.com/fedora-infra/nuancier/pull/82
