### ISSUE TITLE
Release schedule is messed up in the elections tab

### ISSUE THREAD

**Issue by robyduck** [fedora-infra/nuancier#76]
Just noted that the elections tab has 4 Fedora release submission schedules inside. Unfortunately they are not in a chronological order. Any chance to fix that?

**Comment by farhaanbukhsh** [comment]
@robyduck  Hey i was looking into this and i narrowed it down that is i get elections list in template in order that will make it right. But then I looked into this file and this line 
https://github.com/fedora-infra/nuancier/blob/master/nuancier/lib/model.py#L211

and it is returning it in order . So I am a bit confused why its not displaying it in order. I thought of sorting the date in template but that will be a bad practice right.

**Comment by pypingou** [comment]
We could order them by year and date or publication of the results. This should fix this :)

**Comment by robyduck** [comment]
Agree with pingou here, date of publication of the results seems reasonable to me. I think actually it inverts the order when we have two elections in the same year.
