### ISSUE TITLE
make zoom the default action, not tick

### ISSUE THREAD

**Issue by kparal** [fedora-infra/nuancier#77]
This applies when voting for wallpapers.

When I click in the middle of a picture, I expect it to enlarge, not to "vote" for it. Currently when you click anywhere, it votes for the picture, and you have to be really precise for zooming the picture (click exactly on the zoom icon). Please make it the other way round. People are likely to look at many more pictures than they're going to vote for, so zoom functionality is the much more common one and should be much easier. Make zoom the default action, and make voting the precise action.

This will also allow to open the pictures in a new tab easily by middle clicking them. Currently you have to middle click the zoom icon, which is very hard to find out.

**Comment by pypingou** [comment]
@ryanlerch thoughts on this one?

**Comment by pypingou** [comment]
@kparal btw, which screen and screen size do you have, the icons aren't so tiny for me here so I wonder if there isn't something else that's making your experience unpleasant (cf also one of your other tickets).

**Comment by kparal** [comment]
1920x1080 on a 14" screen. The icon size is not that much of a problem, but discoverability bit me hard. I wanted to vote on wallpapers, but the lightbox approach of showing them was unusable for me - the minor issue was that I wanted to see them fullscreen and lightbox doesn't allow that, and the major issue was that image loading was extremely slow (I don't know whether the bandwidth issues are at the image hosting, or somewhere along the way), so I was staring 30 seconds at a white box until the image finally showed. Only then I was able to go and see another wallpaper. That was not going to work. So I wanted to open all the interesting wallpapers into tabs, so that they're downloaded on the background continuously (and I don't have to wait for them one by one). But I couldn't find any way to open them in tabs - left click voted, middle click didn't work, right click didn't either. So I almost left frustrated.

But when closing the page, I had a miraculous idea - what would a middle click performed exactly over the zoom button do? Heureka, wallpaper opened in tab, loaded in background!

So that's my experience. I don't object to the lightbox (although I consider it a worse experience then just opening the image directly in a new tab), maybe somebody likes that. But it should be possible to open it in a background tab easily - by middle clicking/right clicking the thumbnail in the center. Which means the zoom action should be the default, not the vote action. (Also, I don't understand how someone could vote for a thumbnail without enlarging it first. That also suggests zooming being the default action and voting being the specific one).

**Comment by pypingou** [comment]
I have the code ready to do this but I would like to hear @ryanlerch 's opinion from a UX point of view.

**Comment by pypingou** [comment]
Something I've been thinking/playing with was to have a smaller version of the images in lightbox so that it takes less time to load.
The problem then is that I have to limit the size of the image (I put 1024px by default) and users won't be able to actually see the image full-size on the page where they vote (they would be able to on the results page though).

Thoughts on this?

**Comment by kparal** [comment]
Hmm, is that directly related to the original problem, or is that yet another fix to go along with it? The original problem was that the default action should be zoom, not vote. If you speed up image loading in lightbox by shrinking the size, I don't have any strong feelings about that (it's faster, but it's smaller), because I don't really like lightboxes - I have never seen any which actually worked well. I rather open 20 background tabs and let it load in full size while doing something else, than actively waiting for each individual picture. So, hmm, /me shrugs :)

**Comment by pypingou** [comment]
It's a different question but kinda related if the default action becomes zoom-in as then more people will zoom-in and lightbox and large file aren't doing so great together

**Comment by kparal** [comment]
I think the same number of people will zoom in, I don't expect anyone to have voted based just on a tiny thumbnail. Maybe even fewer people will use the lightbox than before, because it will (hopefully) be easier to open the image in a new tab, avoiding the lightbox.
