### ISSUE TITLE
received "Wrong input submitted" after voting

### ISSUE THREAD

**Issue by kparal** [fedora-infra/nuancier#78]
I voted for supplemental wallpapers and received a page "Wrong input submitted" red text and a Back button.

I hit Back, again Submit votes, again the same error.

I have opened the same election in a different tab, my votes were empty there. Then I went back to the original tab, hit Submit votes the third time, and miraculously it worked.

**Comment by pypingou** [comment]
Did you by any chance take more than 20 minutes to submit your vote?
I fear the error is related to the CSRF token that expires after 20 minutes and it's the only reason I can think of that would invalidate the first two attempt.

**Comment by kparal** [comment]
That could be it. It almost certainly took me more than 20 minutes to vote, because there were many wallpapers, the bandwidth was slow, and I was not in rush. Can this be improved somehow? At least informing people would be helpful (countdown at the top?). I'm afraid many people will hit this in this case - there's like 100 images to see and that takes a while.

**Comment by pypingou** [comment]
I know that you are at least the second one to have faced this issue, we'll have to look into making the time-out longer for this page.

**Comment by nphilipp** [comment]
Perhaps "ping" the backend somehow to renew the CRSF token every time an image is opened for viewing?

**Comment by pypingou** [comment]
@nphilipp that would be an idea, although I'm afraid adding some sort of API to get a new csrf token might defeat a little the purpose of the csrf token :-s

**Comment by nphilipp** [comment]
Well, it seems to be what the banks do to extend your session lifetime, so it must be safe ;).

IMO the CRSF should be valid long enough that the user can comfortably complete the task at hand—and reviewing and voting on more than a hundred photos takes a little longer than say change your email address. At any rate, the work shouldn't be lost, at max people should need to reauthenticate.

**Comment by kparal** [comment]
Several people told me that they tried to vote for wallpapers, but received an error, so they didn't in the end (they didn't go through the hassle of reselecting all their votes and submitting again, especially if they weren't sure whether they would receive the same error again).

**Comment by kparal** [comment]
Another wallpaper election, another `Wrong input submitted` error. Sigh.
