### ISSUE TITLE
elections don't show end date

### ISSUE THREAD

**Issue by kparal** [fedora-infra/nuancier#79]
In the list of elections, I see when a vote started, but it's not visible when it ends. So I don't know how much time I have to vote. If I open the election, again there's no information about the duration.

**Comment by pypingou** [comment]
In this list https://apps.fedoraproject.org/nuancier/elections/ ? It's the last column.

**Comment by kparal** [comment]
Oh, I just read "Published" and assumed it means the date when the vote was created. Or maybe people can think it's the date when the results are published (that is not the same as end of voting).

Can we rename this to "Votes closed", if it is really the intended meaning?

**Comment by pypingou** [comment]
The date the results are published is the date the vote is ending, there is no notion of embargo in nuancier as we have in election.
