### ISSUE TITLE
do not remove image when I pick it as a favorite

### ISSUE THREAD

**Issue by kparal** [fedora-infra/nuancier#80]
Every time I pick an image as favorite and put it into the "to be voted for" right bar, the image disappears from the list. That has these consequences:
1) It re-shuffles all the remaining images.
2) I can't display the image again. Which is quite ironic, because when I want to decide between several favorite images, I want to compare them. But I can't, because they're gone from the list.
3) The only way to see which images I have in my "to be voted for" queue are the tiny tiny microscopic previews at the right bar. It's hard to recognize what the image was.
4) When I un-favorite an image (e.g. just to be able to look at it properly once again), it's not added to its original place, but often somewhere else (to the end, it seemed).

Please do not remove a favorited image from the list. Just mark it as selected, e.g. with a colored border around it. That will be obvious, and will allow people to still display the full-sized version later. It will also avoid image shuffling issues.

**Comment by pypingou** [comment]
Sounds reasonable

**Comment by ryanlerch** [comment]
Seems like it could work -- just keep them in the queue on the left, and mark them with a check or something -- but still show them on the right id they have been marked.

Having them disappear worked better for the initial idea of only voting for 5 posts, but that changed, so the thumbnails on the right had to shrink for the 15 choices we offered people 

long story short -- this could work.
